apiVersion: tco.coreos.com/v1
kind: AppVersion
metadata:
  name: kube-core
  namespace: tectonic-system
  labels:
    managed-by-channel-operator: "true"
spec:
  paused: false
status:
  paused: false
upgradereq: 0
upgradecomp: 0
